import re
# re.findall('Total_Goals.\.Under_1\.5','10218695Total_Goals3.Under_1.5',re.IGNORECASE)


raw_rules = [
    {'match':'Total_Goals\d\.Under_0\.5','is_regex':1,'selection_id':120,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_0\.5','is_regex':1,'selection_id':110,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Under_1\.5','is_regex':1,'selection_id':121,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_1\.5','is_regex':1,'selection_id':111,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Under_2\.5','is_regex':1,'selection_id':122,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_2\.5','is_regex':1,'selection_id':112,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Under_3\.5','is_regex':1,'selection_id':123,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_3\.5','is_regex':1,'selection_id':113,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Under_4\.5','is_regex':1,'selection_id':124,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_4\.5','is_regex':1,'selection_id':114,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Under_5\.5','is_regex':1,'selection_id':125,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_5\.5','is_regex':1,'selection_id':115,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Under_6\.5','is_regex':1,'selection_id':126,'market_id':8,'sport_id':1},
    {'match':'Total_Goals\d\.Over_6\.5','is_regex':1,'selection_id':116,'market_id':8,'sport_id':1},
    {'match':'Both_Teams_To_Score\.yes','is_regex':0,'selection_id':104,'market_id':13,'sport_id':1},
    {'match':'Both_Teams_To_Score\.no','is_regex':0,'selection_id':105,'market_id':13,'sport_id':1},
    {'match':'Result.HD','is_regex':0,'selection_id':94,'market_id':5,'sport_id':1},
    {'match':'Result.HA','is_regex':0,'selection_id':93,'market_id':5,'sport_id':1},
    {'match':'Result.AD','is_regex':0,'selection_id':95,'market_id':5,'sport_id':1},
    {'match':'Result_-_1st_Half0.HD','is_regex':0,'selection_id':97,'market_id':6,'sport_id':1},
    {'match':'Result_-_1st_Half0.HA','is_regex':0,'selection_id':96,'market_id':6,'sport_id':1},
    {'match':'Result_-_1st_Half0.AD','is_regex':0,'selection_id':98,'market_id':6,'sport_id':1},
    {'match':'Result_-_2nd_Half0.HD','is_regex':0,'selection_id':100,'market_id':7,'sport_id':1},
    {'match':'Result_-_2nd_Half0.HA','is_regex':0,'selection_id':99,'market_id':7,'sport_id':1},
    {'match':'Result_-_2nd_Half0.AD','is_regex':0,'selection_id':101,'market_id':7,'sport_id':1},
    {'match':'Result_-_1st_Half.RN_H','is_regex':0,'selection_id':4,'market_id':2,'sport_id':1},
    {'match':'Result_-_1st_Half.RN_D','is_regex':0,'selection_id':6,'market_id':2,'sport_id':1},
    {'match':'Result_-_1st_Half.RN_A','is_regex':0,'selection_id':5,'market_id':2,'sport_id':1},
    {'match':'Result_-_2nd_Half.RN_H','is_regex':0,'selection_id':7,'market_id':3,'sport_id':1},
    {'match':'Result_-_2nd_Half.RN_D','is_regex':0,'selection_id':9,'market_id':3,'sport_id':1},
    {'match':'Result_-_2nd_Half.RN_A','is_regex':0,'selection_id':8,'market_id':3,'sport_id':1},
    {'match':'Total_Goals13.odd','is_regex':0,'selection_id':11,'market_id':17,'sport_id':1},
    {'match':'Total_Goals13.even','is_regex':0,'selection_id':10,'market_id':17,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_0\.5','is_regex':1,'selection_id':140,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_0\.5','is_regex':1,'selection_id':130,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_1\.5','is_regex':1,'selection_id':141,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_1\.5','is_regex':1,'selection_id':131,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_2\.5','is_regex':1,'selection_id':142,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_2\.5','is_regex':1,'selection_id':132,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_3\.5','is_regex':1,'selection_id':143,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_3\.5','is_regex':1,'selection_id':133,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_4\.5','is_regex':1,'selection_id':144,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_4\.5','is_regex':1,'selection_id':134,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_5\.5','is_regex':1,'selection_id':145,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_5\.5','is_regex':1,'selection_id':135,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Under_6\.5','is_regex':1,'selection_id':146,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_1st_Half\d\.Over_6\.5','is_regex':1,'selection_id':136,'market_id':11,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_0\.5','is_regex':1,'selection_id':160,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_0\.5','is_regex':1,'selection_id':150,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_1\.5','is_regex':1,'selection_id':161,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_1\.5','is_regex':1,'selection_id':151,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_2\.5','is_regex':1,'selection_id':162,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_2\.5','is_regex':1,'selection_id':152,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_3\.5','is_regex':1,'selection_id':163,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_3\.5','is_regex':1,'selection_id':153,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_4\.5','is_regex':1,'selection_id':164,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_4\.5','is_regex':1,'selection_id':154,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_5\.5','is_regex':1,'selection_id':165,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_5\.5','is_regex':1,'selection_id':155,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Under_6\.5','is_regex':1,'selection_id':166,'market_id':12,'sport_id':1},
    {'match':'Total_Goals_-_2nd_Half\d\.Over_6\.5','is_regex':1,'selection_id':156,'market_id':12,'sport_id':1},
    {'match':'.*Penalty_Kick\.yes','is_regex':1,'selection_id':102,'market_id':19,'sport_id':1},
    {'match':'.*Penalty_Kick\.no','is_regex':1,'selection_id':103,'market_id':19,'sport_id':1},
    {'match':'Both_Teams_To_Score_-_1st_Half.yes','is_regex':0,'selection_id':106,'market_id':14,'sport_id':1},
    {'match':'Both_Teams_To_Score_-_1st_Half.no','is_regex':0,'selection_id':107,'market_id':14,'sport_id':1},
    {'match':'Both_Teams_To_Score_-_2nd_Half.yes','is_regex':0,'selection_id':108,'market_id':15,'sport_id':1},
    {'match':'Both_Teams_To_Score_-_2nd_Half.no','is_regex':0,'selection_id':109,'market_id':15,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_0\.5','is_regex':1,'selection_id':180,'market_id':9,'sport_id':1},   # 10218695Total_Goals_(First_Team).Under_1.5
    {'match':'Total_Goals_\(First_Team\)\.Over_0\.5','is_regex':1,'selection_id':170,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_1\.5','is_regex':1,'selection_id':181,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Over_1\.5','is_regex':1,'selection_id':171,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_2\.5','is_regex':1,'selection_id':182,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Over_2\.5','is_regex':1,'selection_id':172,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_3\.5','is_regex':1,'selection_id':183,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Over_3\.5','is_regex':1,'selection_id':173,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_4\.5','is_regex':1,'selection_id':184,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Over_4\.5','is_regex':1,'selection_id':174,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_5\.5','is_regex':1,'selection_id':185,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Over_5\.5','is_regex':1,'selection_id':175,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Under_6\.5','is_regex':1,'selection_id':186,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(First_Team\)\.Over_6\.5','is_regex':1,'selection_id':176,'market_id':9,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_0\.5','is_regex':1,'selection_id':200,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_0\.5','is_regex':1,'selection_id':190,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_1\.5','is_regex':1,'selection_id':201,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_1\.5','is_regex':1,'selection_id':191,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_2\.5','is_regex':1,'selection_id':202,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_2\.5','is_regex':1,'selection_id':192,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_3\.5','is_regex':1,'selection_id':203,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_3\.5','is_regex':1,'selection_id':193,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_4\.5','is_regex':1,'selection_id':204,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_4\.5','is_regex':1,'selection_id':194,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_5\.5','is_regex':1,'selection_id':205,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_5\.5','is_regex':1,'selection_id':195,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Under_6\.5','is_regex':1,'selection_id':206,'market_id':10,'sport_id':1},
    {'match':'Total_Goals_\(Second_Team\)\.Over_6\.5','is_regex':1,'selection_id':196,'market_id':10,'sport_id':1},
    {'match':'Correct_Score.0_0','is_regex':0,'selection_id':12,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_1','is_regex':0,'selection_id':13,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_2','is_regex':0,'selection_id':14,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_3','is_regex':0,'selection_id':15,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_4','is_regex':0,'selection_id':16,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_5','is_regex':0,'selection_id':17,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_6','is_regex':0,'selection_id':18,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_7','is_regex':0,'selection_id':19,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_8','is_regex':0,'selection_id':20,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.0_9','is_regex':0,'selection_id':21,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_0','is_regex':0,'selection_id':22,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_1','is_regex':0,'selection_id':23,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_2','is_regex':0,'selection_id':24,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_3','is_regex':0,'selection_id':25,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_4','is_regex':0,'selection_id':26,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_5','is_regex':0,'selection_id':27,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_6','is_regex':0,'selection_id':28,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_7','is_regex':0,'selection_id':29,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_8','is_regex':0,'selection_id':30,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.1_9','is_regex':0,'selection_id':31,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_0','is_regex':0,'selection_id':32,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_1','is_regex':0,'selection_id':33,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_2','is_regex':0,'selection_id':34,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_3','is_regex':0,'selection_id':35,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_4','is_regex':0,'selection_id':36,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_5','is_regex':0,'selection_id':37,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_6','is_regex':0,'selection_id':38,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_7','is_regex':0,'selection_id':39,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_8','is_regex':0,'selection_id':40,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.2_9','is_regex':0,'selection_id':41,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_0','is_regex':0,'selection_id':42,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_1','is_regex':0,'selection_id':43,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_2','is_regex':0,'selection_id':44,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_3','is_regex':0,'selection_id':45,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_4','is_regex':0,'selection_id':46,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_5','is_regex':0,'selection_id':47,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_6','is_regex':0,'selection_id':48,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_7','is_regex':0,'selection_id':49,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.3_8','is_regex':0,'selection_id':50,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_0','is_regex':0,'selection_id':51,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_1','is_regex':0,'selection_id':52,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_2','is_regex':0,'selection_id':53,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_3','is_regex':0,'selection_id':54,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_4','is_regex':0,'selection_id':55,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_5','is_regex':0,'selection_id':56,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_6','is_regex':0,'selection_id':57,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_7','is_regex':0,'selection_id':58,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.4_8','is_regex':0,'selection_id':59,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_0','is_regex':0,'selection_id':60,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_1','is_regex':0,'selection_id':61,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_2','is_regex':0,'selection_id':62,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_3','is_regex':0,'selection_id':63,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_4','is_regex':0,'selection_id':64,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_5','is_regex':0,'selection_id':65,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.5_6','is_regex':0,'selection_id':66,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.6_0','is_regex':0,'selection_id':67,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.6_1','is_regex':0,'selection_id':68,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.6_2','is_regex':0,'selection_id':69,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.6_3','is_regex':0,'selection_id':70,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.6_4','is_regex':0,'selection_id':71,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.6_5','is_regex':0,'selection_id':72,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.7_0','is_regex':0,'selection_id':73,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.7_1','is_regex':0,'selection_id':74,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.7_2','is_regex':0,'selection_id':75,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.7_3','is_regex':0,'selection_id':76,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.7_4','is_regex':0,'selection_id':77,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.8_0','is_regex':0,'selection_id':78,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.8_1','is_regex':0,'selection_id':79,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.8_2','is_regex':0,'selection_id':80,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.8_3','is_regex':0,'selection_id':81,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.8_4','is_regex':0,'selection_id':82,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_0','is_regex':0,'selection_id':83,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_1','is_regex':0,'selection_id':84,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_2','is_regex':0,'selection_id':85,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_3','is_regex':0,'selection_id':86,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_4','is_regex':0,'selection_id':87,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_5','is_regex':0,'selection_id':88,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_6','is_regex':0,'selection_id':89,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_7','is_regex':0,'selection_id':90,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_8','is_regex':0,'selection_id':91,'market_id':16,'sport_id':1},
    {'match':'Correct_Score.9_9','is_regex':0,'selection_id':92,'market_id':16,'sport_id':1},
    {'match':'1st_Half___Full_Time.AA','is_regex':0,'selection_id':216,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.AD','is_regex':0,'selection_id':217,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.AH','is_regex':0,'selection_id':218,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.DA','is_regex':0,'selection_id':219,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.DD','is_regex':0,'selection_id':220,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.DH','is_regex':0,'selection_id':221,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.HA','is_regex':0,'selection_id':222,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.HD','is_regex':0,'selection_id':223,'market_id':18,'sport_id':1},
    {'match':'1st_Half___Full_Time.HH','is_regex':0,'selection_id':224,'market_id':18,'sport_id':1},
    {'match':'Match_Result.1','is_regex':0,'selection_id':1,'market_id':1,'sport_id':1},
    {'match':'Match_Result.3','is_regex':0,'selection_id':2,'market_id':1,'sport_id':1},
    {'match':'Match_Result.draw','is_regex':0,'selection_id':3,'market_id':1,'sport_id':1},
    {'match':'Match_Result.1','is_regex':0,'selection_id':1,'market_id':4,'sport_id':2}, # Tennis
    {'match':'Match_Result.3','is_regex':0,'selection_id':2,'market_id':4,'sport_id':2},
    {'match':'Match_Winner_Including_All_OT.HB_H','is_regex':0,
        'selection_id':1,
        'market_id':4,

        'selection_id_inverso':2,
        'market_id_inverso':4,

        'sport_id':3,
     },   # Basket
    {'match':'Match_Winner_Including_All_OT.HB_A','is_regex':0,
        'selection_id':2,
        'market_id':4,

        'selection_id_inverso':1,
        'market_id_inverso':4,

        'sport_id':3
     },
    # {'match':'Match_Result.1','is_regex':0,'selection_id':1,'market_id':4,'sport_id':4}, # Tennis Tavolo / ping pog
    # {'match':'Match_Result.3','is_regex':0,'selection_id':2,'market_id':4,'sport_id':4},
    {'match':'To_Win_Match.1','is_regex':0,'selection_id':1,'market_id':4,'sport_id':4}, # Tennis Tavolo / ping pog
    {'match':'To_Win_Match.3','is_regex':0,'selection_id':2,'market_id':4,'sport_id':4},
]

d = dict()
for i in  raw_rules:
    sport_id = i['sport_id']
    d[sport_id] = dict()
for i in raw_rules:
    sport_id = i['sport_id']
    key = i['match']
    d[sport_id][key] = i

mappatura = d

def data_selection_key_2_ninja(txt, sport_id):
    global mappatura
    testo = txt.split("@")[1]
    if testo in mappatura[sport_id]:
        return mappatura[sport_id][testo]

    # provo a fare i match con le regex che trovo
    for i in raw_rules:
        if i['is_regex'] == 1:
            pattern = i['match']
            if len(re.findall(pattern, testo, re.IGNORECASE)) >0:
                return i

    return False

if __name__ == '__main__':
    # print( data_selection_key_2_ninja('10218695@Total_Goals_(First_Team).Under_1.5', sport_id=1))
    # print( data_selection_key_2_ninja('10244200@Match_Winner_Including_All_OT.HB_H', sport_id=3))
    print( data_selection_key_2_ninja('10244200@Match_Winner_Including_All_OT.HB_H', sport_id=3))